# Use official Bun image
FROM oven/bun:1.1.13

# Set working directory
WORKDIR /app

# Copy dependencies
COPY bun.lock package.json ./

# Install dependencies
RUN bun install

# Copy rest of the app
COPY . .

# Expose your app port (default for Express is 3000)
EXPOSE 3000

# Start the app
CMD ["bun", "run", "start"]
